apiVersion: v1
kind: Namespace
metadata:
  name: java-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: java-namespace
spec:
  selector:
    matchLabels:
      name: java-k8s
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: java-k8s
    spec:
      containers:
      - name: java-app
        image: kozijakinfo/java:1.0
        ports:
          - containerPort: 8080
